[[sources]]
  name   = "dht22"
  errorhandler = "errorhandler"
  [[sources.values]]
    name = "temp"
    handlers = [
      "send_monitor",
      "handler4m2x.send_m2x",
      #"save"
    ]
  [[sources.values]]
    name = "humidity"
    handlers = [
      "send_monitor",
      "handler4m2x.send_m2x",
      #"save"
    ]
  [[sources.values]]
    name = "humiditydeficit"
    handlers = [
      "send_monitor",
      "handler4m2x.send_m2x",
      #"save"
    ]


#[[sources]]
#  name   = "mh-z19"
#  [[sources.values]]
#    name = "co2"
#    handlers = [
#      "send", "save"
#  ]
