[[sources]]
  name   = "dht22"
  errorhandler = "errorhandler"
  [[sources.values]]
    name = "temp"
    handlers = [
      "send_monitor",
#      "handler4m2x.send_m2x",
    ]
  [[sources.values]]
    name = "humidity"
    handlers = [
      "send_monitor",
#      "handler4m2x.send_m2x",
    ]
  [[sources.values]]
    name = "humiditydeficit"
    handlers = [
      "send_monitor",
#      "handler4m2x.send_m2x",
    ]
