[[sensors]]
  handler = "dht22"
  [[sensors.values]]
    name = "temp"
    handlers = [
      "send_monitor"
    ]
  [[sensors.values]]
    name = "humidity"
    handlers = [
      "send_monitor"
    ]
  [[sensors.values]]
    name = "humiditydeficit"
    handlers = [
      "send_monitor"
    ]
